2025-01-14 20:18:02 [INFO] MainScript: Loading configuration from /Users/yuval/MetaMorphic/configs/first.yaml
2025-01-14 20:18:02 [INFO] MainScript: ConfigParser initialized with config path: /Users/yuval/MetaMorphic/configs/first.yaml
2025-01-14 20:18:02 [INFO] MainScript: Attempting to load configuration from: /Users/yuval/MetaMorphic/configs/first.yaml
2025-01-14 20:18:02 [INFO] MainScript: Configuration loaded successfully.
2025-01-14 20:18:02 [INFO] MainScript: Retrieving output file setting from 'settings'...
2025-01-14 20:18:02 [INFO] MainScript: Retrieving default join type from 'settings'...
2025-01-14 20:18:02 [INFO] MainScript: Retrieving files configuration from 'files'...
2025-01-14 20:18:02 [INFO] MainScript: Retrieving joins configuration from 'joins'...
2025-01-14 20:18:02 [INFO] MainScript: Output file: output/merged_data.csv
2025-01-14 20:18:02 [INFO] MainScript: Default join type: left
2025-01-14 20:18:02 [INFO] MainScript: Files definition:
[{'name': 'file3', 'path': 'sample/batch1/file3.csv', 'keys': ['id'], 'transformations': {'select_columns': ['id', 'customer_name', 'email']}}, {'name': 'file4', 'path': 'sample/batch1/file4.csv', 'keys': ['customer_id'], 'transformations': {'rename_columns': {'customer_id': 'id'}, 'filter_rows': {'status': 'complete'}}}, {'name': 'file5', 'path': 'sample/batch1/file5.csv', 'keys': ['order_id'], 'transformations': {'select_columns': ['order_id', 'payment_method', 'amount']}}]
2025-01-14 20:18:02 [INFO] MainScript: Join steps:
[{'source': 'main_data', 'join_with': 'orders', 'join_type': 'inner', 'on': {}}, {'source': 'main_data', 'join_with': 'payments', 'join_type': 'left', 'on': {}}]
2025-01-14 20:18:11 [INFO] MainScript: Loading data from sample/batch1/file3.csv as csv
2025-01-14 20:18:11 [ERROR] MainScript: Error loading data from sample/batch1/file3.csv: [Errno 2] No such file or directory: 'sample/batch1/file3.csv'
Traceback (most recent call last):
  File "/Users/yuval/MetaMorphic/src/data_loader.py", line 14, in load_data
    df = pd.read_csv(file_path)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'sample/batch1/file3.csv'
2025-01-14 20:18:22 [INFO] MainScript: Loading data from sample/batch1/file3.csv as csv
2025-01-14 20:18:22 [ERROR] MainScript: Error loading data from sample/batch1/file3.csv: [Errno 2] No such file or directory: 'sample/batch1/file3.csv'
Traceback (most recent call last):
  File "/Users/yuval/MetaMorphic/src/data_loader.py", line 14, in load_data
    df = pd.read_csv(file_path)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'sample/batch1/file3.csv'
2025-01-14 20:18:30 [INFO] MainScript: Loading data from sample/batch1/file3.csv as csv
2025-01-14 20:18:30 [ERROR] MainScript: Error loading data from sample/batch1/file3.csv: [Errno 2] No such file or directory: 'sample/batch1/file3.csv'
Traceback (most recent call last):
  File "/Users/yuval/MetaMorphic/src/data_loader.py", line 14, in load_data
    df = pd.read_csv(file_path)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'sample/batch1/file3.csv'
2025-01-14 20:18:33 [INFO] MainScript: Loading data from sample/batch1/file3.csv as csv
2025-01-14 20:18:33 [ERROR] MainScript: Error loading data from sample/batch1/file3.csv: [Errno 2] No such file or directory: 'sample/batch1/file3.csv'
Traceback (most recent call last):
  File "/Users/yuval/MetaMorphic/src/data_loader.py", line 14, in load_data
    df = pd.read_csv(file_path)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'sample/batch1/file3.csv'
2025-01-14 20:18:36 [INFO] MainScript: Loading data from sample/batch1/file3.csv as csv
2025-01-14 20:18:36 [ERROR] MainScript: Error loading data from sample/batch1/file3.csv: [Errno 2] No such file or directory: 'sample/batch1/file3.csv'
Traceback (most recent call last):
  File "/Users/yuval/MetaMorphic/src/data_loader.py", line 14, in load_data
    df = pd.read_csv(file_path)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/Users/yuval/opt/anaconda3/lib/python3.9/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'sample/batch1/file3.csv'
